name: pm6-ml
channels:
- conda-forge
- pkgs/main
dependencies:
- aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
- aiohttp=3.13.2=py313h2082a12_0
- aiosignal=1.4.0=pyhd8ed1ab_0
- attrs=25.4.0=pyh71513ae_0
- biopython=1.85=py313h72d1ebd_0
- bottleneck=1.4.2=py313h03d0aa3_1
- brotli-python=1.2.0=py313h79bbab8_0
- bzip2=1.0.8=hd037594_8
- c-ares=1.34.5=h5505292_0
- ca-certificates=2025.11.4=hca03da5_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- certifi=2025.10.5=py313hca03da5_0
- cffi=2.0.0=py313h224173a_1
- charset-normalizer=3.4.4=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_1
- cpython=3.13.9=py313hd8ed1ab_101
- dftd3-python=1.2.1=py313h6535dbc_1
- filelock=3.20.0=pyhd8ed1ab_0
- frozenlist=1.7.0=py313hf28abc0_0
- fsspec=2025.10.0=pyhd8ed1ab_0
- gmp=6.3.0=h7bae524_2
- gmpy2=2.2.1=py313h6d8efe1_1
- h2=4.3.0=pyhcf101f3_0
- h5py=3.15.1=nompi_py313h7aa1c8b_100
- hdf5=1.14.6=nompi_he65715a_103
- hpack=4.1.0=pyhd8ed1ab_0
- hyperframe=6.1.0=pyhd8ed1ab_0
- icu=75.1=hfee45f7_0
- idna=3.11=pyhd8ed1ab_0
- jinja2=3.1.6=pyhd8ed1ab_0
- khronos-opencl-icd-loader=2024.10.24=h5505292_1
- krb5=1.21.3=h237132a_0
- libabseil=20250512.1=cxx17_hd41c47c_0
- libaec=1.1.4=h51d1e36_0
- libblas=3.9.0=38_h51639a9_openblas
- libcblas=3.9.0=38_hb0561ab_openblas
- libcurl=8.17.0=hdece5d2_0
- libcxx=21.1.5=hf598326_0
- libedit=3.1.20250104=pl5321hafb1f1b_0
- libev=4.33=h93a5062_2
- libexpat=2.7.1=hec049ff_0
- libffi=3.5.2=he5f378a_0
- libgfortran=15.2.0=hfcf01ff_1
- libgfortran5=15.2.0=h742603c_1
- liblapack=3.9.0=38_hd9741b5_openblas
- liblzma=5.8.1=h39f12f2_2
- libmpdec=4.0.0=h5505292_0
- libnghttp2=1.67.0=hc438710_0
- libopenblas=0.3.30=openmp_ha158390_3
- libprotobuf=6.31.1=h658db43_2
- libsqlite=3.51.0=h8adb53f_0
- libssh2=1.11.1=h1590b86_0
- libtorch=2.7.1=cpu_generic_hd8f8d4b_4
- libuv=1.51.0=h6caf38d_1
- libzlib=1.3.1=h8359307_2
- lightning=2.5.6=pyhd8ed1ab_0
- lightning-utilities=0.15.2=pyhd8ed1ab_0
- llvm-openmp=21.1.5=h4a912ad_0
- markupsafe=3.0.3=py313h7d74516_0
- mctc-lib=0.4.1=hdbc710d_0
- mmcif_pdbx=2.0.1=pyhd8ed1ab_1
- mpc=1.3.1=h8f1351a_1
- mpfr=4.2.1=hb693164_3
- mpmath=1.3.0=pyhd8ed1ab_1
- multidict=6.6.3=py313h6347b5a_0
- ncurses=6.5=h5e97a16_3
- networkx=3.5=pyhe01879c_0
- nomkl=1.0=h5ca1d4c_0
- numexpr=2.14.1=py313h5fbe615_0
- numpy=2.3.4=py313h9771d21_0
- ocl_icd_wrapper_apple=1.0.0=h27ca646_0
- opencl-headers=2025.06.13=h286801f_0
- openmm=8.4.0=py313ha7a67b4_0_khronos
- openssl=3.5.4=h5503f6c_0
- optree=0.17.0=py313hc50a443_1
- packaging=25.0=pyh29332c3_1
- pandas=2.3.3=py313h3f644e9_1
- pdb2pqr=3.6.1=pyhd8ed1ab_1
- pdbfixer=1.12=pyhd8ed1ab_0
- pip=25.2=pyh145f28c_0
- propcache=0.3.1=py313ha9b7d5b_0
- propka=3.5.1=pyhecae5ae_2
- psutil=7.1.3=py313h9734d34_0
- pybind11=3.0.1=pyh7a1b43c_0
- pybind11-global=3.0.1=pyhc7ab6ef_0
- pycparser=2.22=pyh29332c3_1
- pyparsing=3.2.5=pyhcf101f3_0
- pysocks=1.7.1=pyha55dd90_7
- python=3.13.9=hfc2f54d_101_cp313
- python-dateutil=2.9.0post0=py313hca03da5_2
- python-tzdata=2025.2=pyhd3eb1b0_0
- python-xxhash=3.6.0=py313hee11f83_0
- python_abi=3.13=8_cp313
- pytorch=2.7.1=cpu_generic_py313_heefb1e6_4
- pytorch-lightning=2.5.5=pyh2a12c56_0
- pytorch_geometric=2.7.0=pyhc455866_0
- pytz=2025.2=py313hca03da5_0
- pyyaml=6.0.3=py313h7d74516_0
- readline=8.2=h1d1bf99_2
- requests=2.32.5=pyhd8ed1ab_0
- scipy=1.16.3=py313h0d10b07_0
- setuptools=80.9.0=pyhff2d567_0
- simple-dftd3=1.2.1=hb42fc24_1
- six=1.17.0=py313hca03da5_0
- sleef=3.9.0=hb028509_0
- sympy=1.14.0=pyh2585a3b_105
- tk=8.6.13=h892fb3f_2
- toml-f=0.4.2=h64a7517_2
- torchmd-net=2.4.11=cpu_py313h4b6355e_0
- torchmetrics=1.8.2=pyhd8ed1ab_0
- tqdm=4.67.1=pyhd8ed1ab_1
- typing-extensions=4.15.0=h396c80c_0
- typing_extensions=4.15.0=pyhcf101f3_0
- tzdata=2025b=h78e105d_0
- urllib3=2.5.0=pyhd8ed1ab_0
- xxhash=0.8.3=haa4e116_0
- yaml=0.2.5=h925e9cb_3
- yarl=1.22.0=py313h7d74516_0
- zstandard=0.25.0=py313h9734d34_0
- zstd=1.5.7=h6491c7d_2

